#version 300 es
// ─── generated by @pylinka/compiler (webgl2 transform-feedback) ─── do not edit ───
precision highp float;
precision highp int;

struct ParticleHot { vec2 pos; vec2 vel; float age; float life; };

struct SystemUniforms {
  vec2 emitterPos;
  vec2 prevEmitterPos;
  vec2 emitterVel;
  float dt;
  float time;
  uint frame;
  uint spawnCount;
  uint capacity;
  uint baseSeed;
};

uniform SystemUniforms U;
uniform vec4 V[10];
uniform uint u_spawnCursor; // cursor-window base, pre-wrapped to [0, capacity)

in vec2 i_pos;
in vec2 i_vel;
in float i_age;
in float i_life;
in uint i_seed;
in uint i_flags;
in vec4 i_color;
in float i_size;
in float i_rot;

out vec2 o_pos;
out vec2 o_vel;
out float o_age;
out float o_life;
flat out uint o_seed;
flat out uint o_flags;
out vec4 o_color;
out float o_size;
out float o_rot;

uint pcg(uint v) {
  uint s = v * 747796405u + 2891336453u;
  uint w = ((s >> ((s >> 28u) + 4u)) ^ s) * 277803737u;
  return (w >> 22u) ^ w;
}
uint hash2(uint a, uint b) { return pcg(a ^ pcg(b)); }
float rand01(uint h) { return float(h) * 2.3283064365386963e-10; }
float srand(uint seed, uint n) { return rand01(hash2(seed, n)); }
float frand(uint seed, uint frame, uint n) { return rand01(hash2(seed, hash2(frame, n))); }
float easeSel_power2_out(float t) { float u = 1.0 - t; return 1.0 - u * u * u; }

const float RUNAWAY = 1e7;

void main() {
  gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
  uint slot = uint(gl_VertexID);
  bool wasAlive = (i_flags & 1u) != 0u;
  uint rel = (slot + U.capacity - u_spawnCursor) % U.capacity;
  bool inWindow = rel < U.spawnCount;

  if (!wasAlive && inWindow) {
    uint i = rel;
    float f = (float(i) + 0.5) / float(U.spawnCount);
    vec2 spawnOrigin = mix(U.prevEmitterPos, U.emitterPos, f);
    uint seed = hash2(U.baseSeed, hash2(slot, U.frame));

  // n1 shape.point
  vec2 t_n1 = V[0].xy;
  // n3 gen.randomRange [stable #0]
  float t_n3 = mix(V[4].x, V[3].x, srand(seed, 0u));
  // n5 gen.randomVec2 [stable #1, #2]
  vec2 t_n5 = mix(V[6].xy, V[5].xy, vec2(srand(seed, 1u), srand(seed, 2u)));
  vec2 o_spawnLocal = t_n1; // output.spawnPosition ← n1
  float o_initLife = t_n3;
  vec2 o_initVel = t_n5;
  uint o_texIndex = 0u;

    o_pos = spawnOrigin + o_spawnLocal;
    o_vel = o_initVel;
    o_life = max(o_initLife, 1e-4);
    o_age = U.dt * (1.0 - f);
    o_seed = seed;
    o_flags = 1u | (o_texIndex << 8u);
    o_color = vec4(1.0);
    o_size = 1.0;
    o_rot = 0.0;
    return;
  }

  if (!wasAlive) {
    o_pos = i_pos; o_vel = i_vel; o_age = i_age; o_life = i_life;
    o_seed = i_seed; o_flags = i_flags;
    o_color = i_color; o_size = i_size; o_rot = i_rot;
    return;
  }

  ParticleHot p;
  p.pos = i_pos; p.vel = i_vel; p.age = i_age; p.life = i_life;
  uint seed = i_seed;
  float ageN = clamp(p.age / p.life, 0.0, 1.0);
  vec2 force = vec2(0.0);
  float dragK = 0.0;
  bool kill = false;
  vec4 outColor = i_color;
  float outSize = i_size;
  float outRot = i_rot;

  // n7 field.gravity
  vec2 t_n7 = V[7].xy;
  // n9 param.ref → windPower
  float t_n9 = V[8].x;
  // n10 param.ref → windDir
  float t_n10 = V[9].x;
  // n11 field.directional
  vec2 t_n11 = vec2(cos(t_n10), sin(t_n10)) * t_n9;
  // n13 gen.colorOverLife [ease=power2.out]
  vec4 t_n13 = mix(V[1], V[2], easeSel_power2_out(ageN));
  force += t_n7; // output.addForce (n8)
  force += t_n11; // output.addForce (n12)
  outColor = t_n13; // output.writeColor (n14)

  p.vel += force * U.dt;
  p.vel *= exp(-dragK * U.dt);
  p.pos += p.vel * U.dt;
  p.age += U.dt;
  bool runaway = any(greaterThan(abs(p.pos), vec2(RUNAWAY)));
  if (p.age >= p.life || kill || runaway) {
    o_pos = p.pos; o_vel = p.vel; o_age = p.age; o_life = p.life;
    o_seed = i_seed; o_flags = i_flags & ~1u;
    o_color = outColor; o_size = outSize; o_rot = outRot;
    return;
  }
  o_pos = p.pos;
  o_vel = p.vel;
  o_age = p.age;
  o_life = p.life;
  o_seed = i_seed;
  o_flags = i_flags;
  o_color = clamp(outColor, vec4(0.0), vec4(1.0));
  o_size = outSize;
  o_rot = outRot;
}