// ─── generated by @pylinka/compiler ─── do not edit ───
struct ParticleHot { pos: vec2f, vel: vec2f, age: f32, life: f32, }
struct ParticleRnd { color: u32, size: f32, rot: f32, }
struct ParticleMeta { seed: u32, flags: u32, }
struct Counters { freeTop: atomic<i32>, aliveCount: atomic<u32>, overflowCount: atomic<u32>, }

struct SystemUniforms {
  emitterPos: vec2f,
  prevEmitterPos: vec2f,
  emitterVel: vec2f,
  dt: f32,
  time: f32,
  frame: u32,
  spawnCount: u32,
  capacity: u32,
  baseSeed: u32,
}

@group(0) @binding(0) var<uniform> U: SystemUniforms;
@group(0) @binding(1) var<uniform> V: array<vec4f, 10>;
@group(0) @binding(2) var<storage, read_write> hot: array<ParticleHot>;
@group(0) @binding(3) var<storage, read_write> rnd: array<ParticleRnd>;
@group(0) @binding(4) var<storage, read_write> meta: array<ParticleMeta>;
@group(0) @binding(5) var<storage, read_write> cnt: Counters;
@group(0) @binding(6) var<storage, read_write> freeList: array<u32>;

fn pcg(v: u32) -> u32 {
  var s = v * 747796405u + 2891336453u;
  let w = ((s >> ((s >> 28u) + 4u)) ^ s) * 277803737u;
  return (w >> 22u) ^ w;
}
fn hash2(a: u32, b: u32) -> u32 { return pcg(a ^ pcg(b)); }
fn rand01(h: u32) -> f32 { return f32(h) * 2.3283064365386963e-10; }
fn srand(seed: u32, n: u32) -> f32 { return rand01(hash2(seed, n)); }
fn frand(seed: u32, frame: u32, n: u32) -> f32 { return rand01(hash2(seed, hash2(frame, n))); }
fn easeSel(t: f32) -> f32 { let u = 1.0 - t; return 1.0 - u * u * u; }

const RUNAWAY: f32 = 1e7;

@compute @workgroup_size(256)
fn update(@builtin(global_invocation_id) gid: vec3u) {
  let slot = gid.x;
  if (slot >= U.capacity) { return; }
  if ((meta[slot].flags & 1u) == 0u) { return; }
  var p = hot[slot];
  let seed = meta[slot].seed;
  let ageN = clamp(p.age / p.life, 0.0, 1.0);
  var force = vec2f(0.0);
  var dragK = 0.0;
  var kill = false;
  var outColor = unpack4x8unorm(rnd[slot].color);
  var outSize = rnd[slot].size;
  var outRot = rnd[slot].rot;

  // n7 field.gravity
  let t_n7 = V[7].xy;
  // n9 param.ref → windPower
  let t_n9 = V[8].x;
  // n10 param.ref → windDir
  let t_n10 = V[9].x;
  // n11 field.directional
  let t_n11 = vec2f(cos(t_n10), sin(t_n10)) * t_n9;
  // n13 gen.colorOverLife [ease=power2.out]
  let t_n13 = mix(V[1], V[2], easeSel(ageN));
  force += t_n7; // output.addForce (n8)
  force += t_n11; // output.addForce (n12)
  outColor = t_n13; // output.writeColor (n14)

  p.vel += force * U.dt;
  p.vel *= exp(-dragK * U.dt);
  p.pos += p.vel * U.dt;
  p.age += U.dt;
  let runaway = any(abs(p.pos) > vec2f(RUNAWAY));
  if (p.age >= p.life || kill || runaway) {
    meta[slot].flags = meta[slot].flags & ~1u;
    let idx = atomicAdd(&cnt.freeTop, 1);
    freeList[u32(idx)] = slot;
    atomicSub(&cnt.aliveCount, 1u);
    return;
  }
  hot[slot] = p;
  rnd[slot].color = pack4x8unorm(clamp(outColor, vec4f(0.0), vec4f(1.0)));
  rnd[slot].size = outSize;
  rnd[slot].rot = outRot;
}