// ─── generated by @pylinka/compiler ─── do not edit ───
struct ParticleHot { pos: vec2f, vel: vec2f, age: f32, life: f32, }
struct ParticleRnd { color: u32, size: f32, rot: f32, }
struct ParticleMeta { seed: u32, flags: u32, }
struct Counters { freeTop: atomic<i32>, aliveCount: atomic<u32>, overflowCount: atomic<u32>, }

struct SystemUniforms {
  emitterPos: vec2f,
  prevEmitterPos: vec2f,
  emitterVel: vec2f,
  dt: f32,
  time: f32,
  frame: u32,
  spawnCount: u32,
  capacity: u32,
  baseSeed: u32,
}

@group(0) @binding(0) var<uniform> U: SystemUniforms;
@group(0) @binding(1) var<uniform> V: array<vec4f, 10>;
@group(0) @binding(2) var<storage, read_write> hot: array<ParticleHot>;
@group(0) @binding(3) var<storage, read_write> rnd: array<ParticleRnd>;
@group(0) @binding(4) var<storage, read_write> pmeta: array<ParticleMeta>;
@group(0) @binding(5) var<storage, read_write> cnt: Counters;
@group(0) @binding(6) var<storage, read_write> freeList: array<u32>;

fn pcg(v: u32) -> u32 {
  var s = v * 747796405u + 2891336453u;
  let w = ((s >> ((s >> 28u) + 4u)) ^ s) * 277803737u;
  return (w >> 22u) ^ w;
}
fn hash2(a: u32, b: u32) -> u32 { return pcg(a ^ pcg(b)); }
fn rand01(h: u32) -> f32 { return f32(h) * 2.3283064365386963e-10; }
fn srand(seed: u32, n: u32) -> f32 { return rand01(hash2(seed, n)); }
fn frand(seed: u32, frame: u32, n: u32) -> f32 { return rand01(hash2(seed, hash2(frame, n))); }

@compute @workgroup_size(64)
fn emit(@builtin(global_invocation_id) gid: vec3u) {
  let i = gid.x;
  if (i >= U.spawnCount) { return; }
  let top = atomicSub(&cnt.freeTop, 1);
  if (top <= 0) {
    atomicAdd(&cnt.freeTop, 1);
    atomicAdd(&cnt.overflowCount, 1u);
    return;
  }
  let slot = freeList[u32(top - 1)];
  let f = (f32(i) + 0.5) / f32(U.spawnCount);
  let spawnOrigin = mix(U.prevEmitterPos, U.emitterPos, f);
  let seed = hash2(U.baseSeed, hash2(slot, U.frame));

  // n1 shape.point
  let t_n1 = V[0].xy;
  // n3 gen.randomRange [stable #0]
  let t_n3 = mix(V[4].x, V[3].x, srand(seed, 0u));
  // n5 gen.randomVec2 [stable #1, #2]
  let t_n5 = mix(V[6].xy, V[5].xy, vec2f(srand(seed, 1u), srand(seed, 2u)));
  let o_spawnLocal: vec2f = t_n1; // output.spawnPosition ← n1
  let o_initLife: f32 = t_n3;
  let o_initVel: vec2f = t_n5;
  let o_texIndex: u32 = 0u;

  hot[slot].pos = spawnOrigin + o_spawnLocal;
  hot[slot].vel = o_initVel;
  hot[slot].life = max(o_initLife, 1e-4);
  hot[slot].age = U.dt * (1.0 - f);
  pmeta[slot].seed = seed;
  pmeta[slot].flags = 1u | (o_texIndex << 8u);
  rnd[slot] = ParticleRnd(0xffffffffu, 1.0, 0.0);
  atomicAdd(&cnt.aliveCount, 1u);
}