/**
 * GLSL ES 3.00 scaffolds for the webgl2 target (REQUIREMENTS.md §13.12,
 * QUESTIONS.md Q-webgl2). WebGL2 has no compute or atomics, so the emit and
 * update kernels fuse into ONE transform-feedback vertex shader over every
 * slot: a dead slot inside the cursor window `[spawnCursor, spawnCursor +
 * spawnCount) mod capacity` runs the generated INIT body; an alive slot runs
 * the generated UPDATE body; anything else passes through. Alive slots in the
 * window simply don't respawn — the documented drop-new approximation of the
 * fallback tier.
 *
 * CompiledSystem field mapping for this target: `emitSrc` = the fused step
 * VERTEX shader (both bodies spliced), `updateSrc` = the rasterizer-discard
 * fragment stage that completes the program.
 */

/** Per-particle interleaved state layout shared by compiler and runtime. */
export interface Webgl2Attrib {
  name: string;
  /** component count */
  size: number;
  /** 'float' → vertexAttribPointer, 'uint' → vertexAttribIPointer */
  type: 'float' | 'uint';
  offsetBytes: number;
}

export interface Webgl2Layout {
  strideBytes: number;
  /** transformFeedbackVaryings capture list (INTERLEAVED_ATTRIBS, this order) */
  varyings: string[];
  attribs: Webgl2Attrib[];
  /** extra uniform beyond SystemUniforms: the cursor-window base (uint) */
  spawnCursorUniform: string;
}

/**
 * hot (pos/vel/age/life) + meta (seed/flags) + rnd (color/size/rot) fused into
 * one 56-byte record — TF writes one interleaved buffer per system.
 */
export const WEBGL2_LAYOUT: Webgl2Layout = {
  strideBytes: 56,
  varyings: ['o_pos', 'o_vel', 'o_age', 'o_life', 'o_seed', 'o_flags', 'o_color', 'o_size', 'o_rot'],
  attribs: [
    { name: 'i_pos', size: 2, type: 'float', offsetBytes: 0 },
    { name: 'i_vel', size: 2, type: 'float', offsetBytes: 8 },
    { name: 'i_age', size: 1, type: 'float', offsetBytes: 16 },
    { name: 'i_life', size: 1, type: 'float', offsetBytes: 20 },
    { name: 'i_seed', size: 1, type: 'uint', offsetBytes: 24 },
    { name: 'i_flags', size: 1, type: 'uint', offsetBytes: 28 },
    { name: 'i_color', size: 4, type: 'float', offsetBytes: 32 },
    { name: 'i_size', size: 1, type: 'float', offsetBytes: 48 },
    { name: 'i_rot', size: 1, type: 'float', offsetBytes: 52 },
  ],
  spawnCursorUniform: 'u_spawnCursor',
};

/** The §13.9 ease function as GLSL, named per distinct ease key. */
export function easeFnGlsl(name: string, easeBodyWgsl: string): string {
  // ease bodies only ever declare `let u` (an f32) — see wgsl.ts EASE_BODIES
  return `float ${name}(float t) { ${easeBodyWgsl.replace(/\blet\s+/g, 'float ')} }`;
}

export interface GlslStepOptions {
  slots: number;
  helpers: { safeDiv: boolean; safeNormalize: boolean };
  /** ease function sources (from easeFnGlsl), one per distinct ease the graph uses */
  easeSrcs?: string[];
  /** generated bodies, already translated to GLSL */
  initBody: string;
  updateBody: string;
  postIntegrate: string;
  /** setVelocity graphs omit the force/drag integration lines (§13.6) */
  setVelocity: boolean;
}

/** The fused transform-feedback step vertex shader. */
export function glslStepShader(o: GlslStepOptions): string {
  const parts: string[] = [];
  parts.push(`#version 300 es
// ─── generated by @pylinka/compiler (webgl2 transform-feedback) ─── do not edit ───
precision highp float;
precision highp int;

struct ParticleHot { vec2 pos; vec2 vel; float age; float life; };

struct SystemUniforms {
  vec2 emitterPos;
  vec2 prevEmitterPos;
  vec2 emitterVel;
  float dt;
  float time;
  uint frame;
  uint spawnCount;
  uint capacity;
  uint baseSeed;
};

uniform SystemUniforms U;
uniform vec4 V[${o.slots}];
uniform uint u_spawnCursor; // cursor-window base, pre-wrapped to [0, capacity)

in vec2 i_pos;
in vec2 i_vel;
in float i_age;
in float i_life;
in uint i_seed;
in uint i_flags;
in vec4 i_color;
in float i_size;
in float i_rot;

out vec2 o_pos;
out vec2 o_vel;
out float o_age;
out float o_life;
flat out uint o_seed;
flat out uint o_flags;
out vec4 o_color;
out float o_size;
out float o_rot;

uint pcg(uint v) {
  uint s = v * 747796405u + 2891336453u;
  uint w = ((s >> ((s >> 28u) + 4u)) ^ s) * 277803737u;
  return (w >> 22u) ^ w;
}
uint hash2(uint a, uint b) { return pcg(a ^ pcg(b)); }
float rand01(uint h) { return float(h) * 2.3283064365386963e-10; }
float srand(uint seed, uint n) { return rand01(hash2(seed, n)); }
float frand(uint seed, uint frame, uint n) { return rand01(hash2(seed, hash2(frame, n))); }`);

  if (o.helpers.safeDiv) {
    parts.push(`
float safeDiv(float a, float b) {
  float s = (b != 0.0) ? sign(b) : 1.0;
  return a / ((abs(b) < 1e-6) ? s * 1e-6 : b);
}`);
  }
  if (o.helpers.safeNormalize) {
    parts.push(`
vec2 safeNormalize(vec2 v) {
  float len = length(v);
  return (len < 1e-6) ? vec2(0.0) : v / len;
}`);
  }
  if (o.easeSrcs !== undefined) for (const src of o.easeSrcs) parts.push(src);

  const integrate = o.setVelocity
    ? ''
    : `  p.vel += force * U.dt;
  p.vel *= exp(-dragK * U.dt);
`;
  const post = o.postIntegrate !== '' ? o.postIntegrate + '\n' : '';

  parts.push(`
const float RUNAWAY = 1e7;

void main() {
  gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
  uint slot = uint(gl_VertexID);
  bool wasAlive = (i_flags & 1u) != 0u;
  uint rel = (slot + U.capacity - u_spawnCursor) % U.capacity;
  bool inWindow = rel < U.spawnCount;

  if (!wasAlive && inWindow) {
    uint i = rel;
    float f = (float(i) + 0.5) / float(U.spawnCount);
    vec2 spawnOrigin = mix(U.prevEmitterPos, U.emitterPos, f);
    uint seed = hash2(U.baseSeed, hash2(slot, U.frame));

${o.initBody}

    o_pos = spawnOrigin + o_spawnLocal;
    o_vel = o_initVel;
    o_life = max(o_initLife, 1e-4);
    o_age = U.dt * (1.0 - f);
    o_seed = seed;
    o_flags = 1u | (o_texIndex << 8u);
    o_color = vec4(1.0);
    o_size = 1.0;
    o_rot = 0.0;
    return;
  }

  if (!wasAlive) {
    o_pos = i_pos; o_vel = i_vel; o_age = i_age; o_life = i_life;
    o_seed = i_seed; o_flags = i_flags;
    o_color = i_color; o_size = i_size; o_rot = i_rot;
    return;
  }

  ParticleHot p;
  p.pos = i_pos; p.vel = i_vel; p.age = i_age; p.life = i_life;
  uint seed = i_seed;
  float ageN = clamp(p.age / p.life, 0.0, 1.0);
  vec2 force = vec2(0.0);
  float dragK = 0.0;
  bool kill = false;
  vec4 outColor = i_color;
  float outSize = i_size;
  float outRot = i_rot;

${o.updateBody}

${integrate}  p.pos += p.vel * U.dt;
${post}  p.age += U.dt;
  bool runaway = any(greaterThan(abs(p.pos), vec2(RUNAWAY)));
  if (p.age >= p.life || kill || runaway) {
    o_pos = p.pos; o_vel = p.vel; o_age = p.age; o_life = p.life;
    o_seed = i_seed; o_flags = i_flags & ~1u;
    o_color = outColor; o_size = outSize; o_rot = outRot;
    return;
  }
  o_pos = p.pos;
  o_vel = p.vel;
  o_age = p.age;
  o_life = p.life;
  o_seed = i_seed;
  o_flags = i_flags;
  o_color = clamp(outColor, vec4(0.0), vec4(1.0));
  o_size = outSize;
  o_rot = outRot;
}`);
  return parts.join('\n');
}

/** Fragment stage completing the TF program (rasterizer discard is on). */
export const GLSL_DISCARD_FS = `#version 300 es
// ─── generated by @pylinka/compiler (webgl2 transform-feedback) ─── do not edit ───
precision mediump float;
out vec4 c;
void main() { c = vec4(0.0); }`;
