/**
 * WGSL scaffolds (REQUIREMENTS.md §13.2–§13.6, §13.9, §13.10). The generated
 * node body is spliced into the fixed kernel templates here; this is the single
 * source of truth for the preamble and kernel shape.
 */

/** Structs + uniforms + bindings + PRNG. `slots` bakes the V array length. */
export function preamble(slots: number, helpers: { safeDiv: boolean; safeNormalize: boolean }): string {
  const parts: string[] = [];
  parts.push(`// ─── generated by @pylinka/compiler ─── do not edit ───
struct ParticleHot { pos: vec2f, vel: vec2f, age: f32, life: f32, }
struct ParticleRnd { color: u32, size: f32, rot: f32, }
struct ParticleMeta { seed: u32, flags: u32, }
struct Counters { freeTop: atomic<i32>, aliveCount: atomic<u32>, overflowCount: atomic<u32>, }

struct SystemUniforms {
  emitterPos: vec2f,
  prevEmitterPos: vec2f,
  emitterVel: vec2f,
  dt: f32,
  time: f32,
  frame: u32,
  spawnCount: u32,
  capacity: u32,
  baseSeed: u32,
}

@group(0) @binding(0) var<uniform> U: SystemUniforms;
@group(0) @binding(1) var<uniform> V: array<vec4f, ${slots}>;
@group(0) @binding(2) var<storage, read_write> hot: array<ParticleHot>;
@group(0) @binding(3) var<storage, read_write> rnd: array<ParticleRnd>;
@group(0) @binding(4) var<storage, read_write> pmeta: array<ParticleMeta>;
@group(0) @binding(5) var<storage, read_write> cnt: Counters;
@group(0) @binding(6) var<storage, read_write> freeList: array<u32>;

fn pcg(v: u32) -> u32 {
  var s = v * 747796405u + 2891336453u;
  let w = ((s >> ((s >> 28u) + 4u)) ^ s) * 277803737u;
  return (w >> 22u) ^ w;
}
fn hash2(a: u32, b: u32) -> u32 { return pcg(a ^ pcg(b)); }
fn rand01(h: u32) -> f32 { return f32(h) * 2.3283064365386963e-10; }
fn srand(seed: u32, n: u32) -> f32 { return rand01(hash2(seed, n)); }
fn frand(seed: u32, frame: u32, n: u32) -> f32 { return rand01(hash2(seed, hash2(frame, n))); }`);

  if (helpers.safeDiv) {
    parts.push(`
fn safeDiv(a: f32, b: f32) -> f32 {
  let s = select(1.0, sign(b), b != 0.0);
  return a / select(b, s * 1e-6, abs(b) < 1e-6);
}`);
  }
  if (helpers.safeNormalize) {
    parts.push(`
fn safeNormalize(v: vec2f) -> vec2f {
  let len = length(v);
  return select(v / len, vec2f(0.0), len < 1e-6);
}`);
  }
  return parts.join('\n');
}

// Easing (§13.9) is centralized in ease.ts — the single source of truth shared
// by the WGSL/GLSL shader backends and the editor's JS curve sampler. Custom
// cubic-bezier curves ride the same `structural.ease` string channel.
export { EASE_BODIES, EASE_KEYS, easeFn, easeFnName } from './ease.js';

/** Emit kernel scaffold (§13.5). `body` is the generated init body (indented).
 *  An emission mask (binding 7) overrides the analytic spawn offset when set:
 *  maskTbl[0].x holds the point count, points follow at indices 1..N. A dummy
 *  1-element buffer (count 0) means "no mask". Declared only here so the update
 *  kernel is unaffected; the shared bind-group layout carries the entry. */
export function emitKernel(body: string): string {
  return `
@group(0) @binding(7) var<storage, read> maskTbl: array<vec2f>;

@compute @workgroup_size(64)
fn emit(@builtin(global_invocation_id) gid: vec3u) {
  let i = gid.x;
  if (i >= U.spawnCount) { return; }
  let top = atomicSub(&cnt.freeTop, 1);
  if (top <= 0) {
    atomicAdd(&cnt.freeTop, 1);
    atomicAdd(&cnt.overflowCount, 1u);
    return;
  }
  let slot = freeList[u32(top - 1)];
  let f = (f32(i) + 0.5) / f32(U.spawnCount);
  let spawnOrigin = mix(U.prevEmitterPos, U.emitterPos, f);
  let seed = hash2(U.baseSeed, hash2(slot, U.frame));

${body}

  var spawnLocal = o_spawnLocal;
  let maskN = u32(maskTbl[0].x);
  if (maskN > 0u) {
    let mi = 1u + min(u32(rand01(hash2(seed, 4919u)) * f32(maskN)), maskN - 1u);
    spawnLocal = maskTbl[mi];
  }
  hot[slot].pos = spawnOrigin + spawnLocal;
  hot[slot].vel = o_initVel;
  hot[slot].life = max(o_initLife, 1e-4);
  hot[slot].age = U.dt * (1.0 - f);
  pmeta[slot].seed = seed;
  pmeta[slot].flags = 1u | (o_texIndex << 8u);
  rnd[slot] = ParticleRnd(0xffffffffu, 1.0, 0.0);
  atomicAdd(&cnt.aliveCount, 1u);
}`;
}

/**
 * Sub-emitter emit kernel: a child system spawns one particle on each PARENT
 * particle death, at the parent's position, running the child's own init body.
 * Detection is transition-based and needs no parent cooperation — the child
 * keeps a shadow of each parent slot's alive bit (`prevAlive`, binding 10) and
 * fires when a slot goes alive→dead. Parent hot/meta are read-only (8/9). The
 * child spawns into its own free-list pool, so its normal update kernel is
 * reused unchanged; its clock-driven `emit` is simply not dispatched.
 * Requires the child capacity to equal the parent capacity (1:1 slot index).
 */
export function subEmitKernel(body: string): string {
  return `
@group(0) @binding(8) var<storage, read> pHot: array<ParticleHot>;
@group(0) @binding(9) var<storage, read> pMeta: array<ParticleMeta>;
@group(0) @binding(10) var<storage, read_write> prevAlive: array<u32>;

@compute @workgroup_size(64)
fn subEmit(@builtin(global_invocation_id) gid: vec3u) {
  let i = gid.x;
  if (i >= U.capacity) { return; }
  let aliveNow = pMeta[i].flags & 1u;
  let wasAlive = prevAlive[i];
  prevAlive[i] = aliveNow;
  if (wasAlive != 1u || aliveNow != 0u) { return; }

  let top = atomicSub(&cnt.freeTop, 1);
  if (top <= 0) {
    atomicAdd(&cnt.freeTop, 1);
    atomicAdd(&cnt.overflowCount, 1u);
    return;
  }
  let slot = freeList[u32(top - 1)];
  let spawnOrigin = pHot[i].pos;
  let seed = hash2(U.baseSeed, hash2(slot, U.frame));

${body}

  hot[slot].pos = spawnOrigin + o_spawnLocal;
  hot[slot].vel = o_initVel;
  hot[slot].life = max(o_initLife, 1e-4);
  hot[slot].age = 0.0;
  pmeta[slot].seed = seed;
  pmeta[slot].flags = 1u | (o_texIndex << 8u);
  rnd[slot] = ParticleRnd(0xffffffffu, 1.0, 0.0);
  atomicAdd(&cnt.aliveCount, 1u);
}`;
}

export interface UpdateOptions {
  /** setVelocity graphs omit the force/drag integration lines (§13.6). */
  setVelocity: boolean;
}

/** Update kernel scaffold (§13.6). `body` is the generated update body;
 *  `postIntegrate` holds writePosition assignments, placed after integration. */
export function updateKernel(body: string, postIntegrate: string, opts: UpdateOptions): string {
  const integrate = opts.setVelocity
    ? ''
    : `  p.vel += force * U.dt;
  p.vel *= exp(-dragK * U.dt);
`;
  const post = postIntegrate ? postIntegrate + '\n' : '';
  return `
const RUNAWAY: f32 = 1e7;

@compute @workgroup_size(256)
fn update(@builtin(global_invocation_id) gid: vec3u) {
  let slot = gid.x;
  if (slot >= U.capacity) { return; }
  if ((pmeta[slot].flags & 1u) == 0u) { return; }
  var p = hot[slot];
  let seed = pmeta[slot].seed;
  let ageN = clamp(p.age / p.life, 0.0, 1.0);
  var force = vec2f(0.0);
  var dragK = 0.0;
  var kill = false;
  var outColor = unpack4x8unorm(rnd[slot].color);
  var outSize = rnd[slot].size;
  var outRot = rnd[slot].rot;

${body}

${integrate}  p.pos += p.vel * U.dt;
${post}  p.age += U.dt;
  let runaway = any(abs(p.pos) > vec2f(RUNAWAY));
  if (p.age >= p.life || kill || runaway) {
    pmeta[slot].flags = pmeta[slot].flags & ~1u;
    let idx = atomicAdd(&cnt.freeTop, 1);
    freeList[u32(idx)] = slot;
    atomicSub(&cnt.aliveCount, 1u);
    return;
  }
  hot[slot] = p;
  rnd[slot].color = pack4x8unorm(clamp(outColor, vec4f(0.0), vec4f(1.0)));
  rnd[slot].size = outSize;
  rnd[slot].rot = outRot;
}`;
}
