/**
 * WGSL scaffolds (REQUIREMENTS.md §13.2–§13.6, §13.9, §13.10). The generated
 * node body is spliced into the fixed kernel templates here; this is the single
 * source of truth for the preamble and kernel shape.
 */

/** Structs + uniforms + bindings + PRNG. `slots` bakes the V array length. */
export function preamble(slots: number, helpers: { safeDiv: boolean; safeNormalize: boolean }): string {
  const parts: string[] = [];
  parts.push(`// ─── generated by @pylinka/compiler ─── do not edit ───
struct ParticleHot { pos: vec2f, vel: vec2f, age: f32, life: f32, }
struct ParticleRnd { color: u32, size: f32, rot: f32, }
struct ParticleMeta { seed: u32, flags: u32, }
struct Counters { freeTop: atomic<i32>, aliveCount: atomic<u32>, overflowCount: atomic<u32>, }

struct SystemUniforms {
  emitterPos: vec2f,
  prevEmitterPos: vec2f,
  emitterVel: vec2f,
  dt: f32,
  time: f32,
  frame: u32,
  spawnCount: u32,
  capacity: u32,
  baseSeed: u32,
}

@group(0) @binding(0) var<uniform> U: SystemUniforms;
@group(0) @binding(1) var<uniform> V: array<vec4f, ${slots}>;
@group(0) @binding(2) var<storage, read_write> hot: array<ParticleHot>;
@group(0) @binding(3) var<storage, read_write> rnd: array<ParticleRnd>;
@group(0) @binding(4) var<storage, read_write> meta: array<ParticleMeta>;
@group(0) @binding(5) var<storage, read_write> cnt: Counters;
@group(0) @binding(6) var<storage, read_write> freeList: array<u32>;

fn pcg(v: u32) -> u32 {
  var s = v * 747796405u + 2891336453u;
  let w = ((s >> ((s >> 28u) + 4u)) ^ s) * 277803737u;
  return (w >> 22u) ^ w;
}
fn hash2(a: u32, b: u32) -> u32 { return pcg(a ^ pcg(b)); }
fn rand01(h: u32) -> f32 { return f32(h) * 2.3283064365386963e-10; }
fn srand(seed: u32, n: u32) -> f32 { return rand01(hash2(seed, n)); }
fn frand(seed: u32, frame: u32, n: u32) -> f32 { return rand01(hash2(seed, hash2(frame, n))); }`);

  if (helpers.safeDiv) {
    parts.push(`
fn safeDiv(a: f32, b: f32) -> f32 {
  let s = select(1.0, sign(b), b != 0.0);
  return a / select(b, s * 1e-6, abs(b) < 1e-6);
}`);
  }
  if (helpers.safeNormalize) {
    parts.push(`
fn safeNormalize(v: vec2f) -> vec2f {
  let len = length(v);
  return select(v / len, vec2f(0.0), len < 1e-6);
}`);
  }
  return parts.join('\n');
}

/** The §13.9 ease function `easeSel`, inlined for exactly one `ease` choice. */
export function easeFn(ease: string): string {
  const body = EASE_BODIES[ease];
  if (body === undefined) throw new Error(`Unknown ease "${ease}"`);
  return `fn easeSel(t: f32) -> f32 { ${body} }`;
}

const EASE_BODIES: Record<string, string> = {
  linear: 'return t;',
  'power1.in': 'return t * t;',
  'power1.out': 'let u = 1.0 - t; return 1.0 - u * u;',
  'power1.inOut': 'if (t < 0.5) { return 2.0 * t * t; } let u = 1.0 - t; return 1.0 - 2.0 * u * u;',
  'power2.in': 'return t * t * t;',
  'power2.out': 'let u = 1.0 - t; return 1.0 - u * u * u;',
  'power2.inOut':
    'if (t < 0.5) { return 4.0 * t * t * t; } let u = 1.0 - t; return 1.0 - 4.0 * u * u * u;',
  'power3.in': 'return t * t * t * t;',
  'power3.out': 'let u = 1.0 - t; return 1.0 - u * u * u * u;',
  'sine.in': 'return 1.0 - cos(t * 1.5707963267948966);',
  'sine.out': 'return sin(t * 1.5707963267948966);',
  'sine.inOut': 'return 0.5 - 0.5 * cos(t * 3.141592653589793);',
  'expo.out': 'if (t >= 1.0) { return 1.0; } return 1.0 - exp2(-10.0 * t);',
  'back.out': 'let u = t - 1.0; return 1.0 + 2.70158 * u * u * u + 1.70158 * u * u;',
};

export const EASE_KEYS = Object.keys(EASE_BODIES);

/** Emit kernel scaffold (§13.5). `body` is the generated init body (indented). */
export function emitKernel(body: string): string {
  return `
@compute @workgroup_size(64)
fn emit(@builtin(global_invocation_id) gid: vec3u) {
  let i = gid.x;
  if (i >= U.spawnCount) { return; }
  let top = atomicSub(&cnt.freeTop, 1);
  if (top <= 0) {
    atomicAdd(&cnt.freeTop, 1);
    atomicAdd(&cnt.overflowCount, 1u);
    return;
  }
  let slot = freeList[u32(top - 1)];
  let f = (f32(i) + 0.5) / f32(U.spawnCount);
  let spawnOrigin = mix(U.prevEmitterPos, U.emitterPos, f);
  let seed = hash2(U.baseSeed, hash2(slot, U.frame));

${body}

  hot[slot].pos = spawnOrigin + o_spawnLocal;
  hot[slot].vel = o_initVel;
  hot[slot].life = max(o_initLife, 1e-4);
  hot[slot].age = U.dt * (1.0 - f);
  meta[slot].seed = seed;
  meta[slot].flags = 1u | (o_texIndex << 8u);
  rnd[slot] = ParticleRnd(0xffffffffu, 1.0, 0.0);
  atomicAdd(&cnt.aliveCount, 1u);
}`;
}

export interface UpdateOptions {
  /** setVelocity graphs omit the force/drag integration lines (§13.6). */
  setVelocity: boolean;
}

/** Update kernel scaffold (§13.6). `body` is the generated update body;
 *  `postIntegrate` holds writePosition assignments, placed after integration. */
export function updateKernel(body: string, postIntegrate: string, opts: UpdateOptions): string {
  const integrate = opts.setVelocity
    ? ''
    : `  p.vel += force * U.dt;
  p.vel *= exp(-dragK * U.dt);
`;
  const post = postIntegrate ? postIntegrate + '\n' : '';
  return `
const RUNAWAY: f32 = 1e7;

@compute @workgroup_size(256)
fn update(@builtin(global_invocation_id) gid: vec3u) {
  let slot = gid.x;
  if (slot >= U.capacity) { return; }
  if ((meta[slot].flags & 1u) == 0u) { return; }
  var p = hot[slot];
  let seed = meta[slot].seed;
  let ageN = clamp(p.age / p.life, 0.0, 1.0);
  var force = vec2f(0.0);
  var dragK = 0.0;
  var kill = false;
  var outColor = unpack4x8unorm(rnd[slot].color);
  var outSize = rnd[slot].size;
  var outRot = rnd[slot].rot;

${body}

${integrate}  p.pos += p.vel * U.dt;
${post}  p.age += U.dt;
  let runaway = any(abs(p.pos) > vec2f(RUNAWAY));
  if (p.age >= p.life || kill || runaway) {
    meta[slot].flags = meta[slot].flags & ~1u;
    let idx = atomicAdd(&cnt.freeTop, 1);
    freeList[u32(idx)] = slot;
    atomicSub(&cnt.aliveCount, 1u);
    return;
  }
  hot[slot] = p;
  rnd[slot].color = pack4x8unorm(clamp(outColor, vec4f(0.0), vec4f(1.0)));
  rnd[slot].size = outSize;
  rnd[slot].rot = outRot;
}`;
}
